export default [
  {
    linguistLanguageId: 183,
    name: 'JavaScript',
    type: 'programming',
    tmScope: 'source.js',
    aceMode: 'javascript',
    codemirrorMode: 'javascript',
    codemirrorMimeType: 'text/javascript',
    color: '#f1e05a',
    aliases: ['js', 'node'],
    extensions: [
      '.js',
      '._js',
      '.bones',
      '.cjs',
      '.es',
      '.es6',
      '.frag',
      '.gs',
      '.jake',
      '.javascript',
      '.jsb',
      '.jscad',
      '.jsfl',
      '.jslib',
      '.jsm',
      '.jspre',
      '.jss',
      '.mjs',
      '.njs',
      '.pac',
      '.sjs',
      '.ssjs',
      '.xsjs',
      '.xsjslib',
      '.wxs',
    ],
    filenames: ['Jakefile'],
    interpreters: [
      'chakra',
      'd8',
      'gjs',
      'js',
      'node',
      'nodejs',
      'qjs',
      'rhino',
      'v8',
      'v8-shell',
      'zx',
    ],
    vscodeLanguageIds: ['javascript', 'mongo'],
  },
  {
    linguistLanguageId: 183,
    name: 'JSX',
    type: 'programming',
    tmScope: 'source.js.jsx',
    aceMode: 'javascript',
    codemirrorMode: 'jsx',
    codemirrorMimeType: 'text/jsx',
    extensions: ['.jsx'],
    vscodeLanguageIds: ['javascriptreact'],
    group: 'JavaScript',
  },
  {
    linguistLanguageId: 378,
    name: 'TypeScript',
    type: 'programming',
    color: '#3178c6',
    aliases: ['ts'],
    interpreters: ['deno', 'ts-node'],
    extensions: ['.ts', '.cts', '.mts'],
    tmScope: 'source.ts',
    aceMode: 'typescript',
    codemirrorMode: 'javascript',
    codemirrorMimeType: 'application/typescript',
    vscodeLanguageIds: ['typescript'],
  },
  {
    linguistLanguageId: 94_901_924,
    name: 'TSX',
    type: 'programming',
    color: '#3178c6',
    group: 'TypeScript',
    extensions: ['.tsx'],
    tmScope: 'source.tsx',
    aceMode: 'javascript',
    codemirrorMode: 'jsx',
    codemirrorMimeType: 'text/jsx',
    vscodeLanguageIds: ['typescriptreact'],
  },
]
