name: CI

on:
  push:
    branches:
      - main
  pull_request:
  # schedule:
  #   - cron: "0 23 * * 6"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        node_version:
          - "19"
          - "18"
        prettier:
          - ""
          - "3.0.0-alpha.4"
        # exclude:
        #   - os: "macos-latest"
        #     node_version: "12"
    name: Node.js ${{ matrix.node_version }} on ${{ matrix.os }} with Prettier@${{ matrix.prettier }}
    runs-on: ${{ matrix.os }}
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install Dependencies
        run: yarn

      - name: Install Prettier
        if: matrix.prettier != ''
        run: yarn up prettier@${{ matrix.prettier }}

      - name: Run Test
        run: yarn test

      # - uses: codecov/codecov-action@v3
      #   with:
      #     fail_ci_if_error: true

  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: yarn

      - name: Run Lint
        run: yarn lint
